### PR TITLE
Fix tsconfig and package types reference.

### PR DESCRIPTION
**Pull request by passabilities**
It:
* Fixes the tsconfig file to only include files from the `src` directory when compiling
* Type definitions are then compiled to the root of the `libs` directory

### CODE REVIEW

**Comment by samholmes** [comment]
These changes deviate from configurations replicated from Disklet:

https://github.com/EdgeApp/disklet/blob/master/package.json#L33
https://github.com/EdgeApp/disklet/blob/master/tsconfig.json#L15

So, I'm not sure if we intend to make these changes; it'd be inconsistent to Disklet's configuration. If this fixes an issue, we might want to consider this fix for Disklet as well.

@passabilities Could you expand on what these changes fix?

**Comment by samholmes** [comment]
Upon discussion with @passabilities, the discovery is that this resolves an issue whereas some unwanted directories were being included in the TS output files (tests). By having a white-list approach (includes directive), we avoid the issue and explicitly define which directory/files is included in the build output (i.e. src).

I'd consider this fix for memlet, but also consider this for disklet as well. This change has already been applied to baselet by this PR: https://github.com/EdgeApp/baselet/pull/8 (approved by @thehobbit85)

**Comment by samholmes** [comment]
@passabilities by removing `test/` from the tsconfig.json (by not including it in "include"), wont this remove type-checking in our unit tests? This is one concern to accepting this change.

@swansontec If you have time, feel free to chime-in and add your perspectives here.

Putting this PR on hold for now.

**Comment by passabilities** [comment]
@samholmes I have the unit tests pulled up and they don't seem to have been effected at all. Removing them from the `tsconfig.json` essentially just means they won't be compiled when typescript runs. Most IDEs should still be able to recognize any types.

**Comment by samholmes** [comment]
@swansontec Do you have any objections or do you see any drawbacks here? The only concern I have at this point is whether it's against conventions and therefore not acceptable.

**Comment by thehobbit85** [comment]
Closing following the response from @swansontec.
In case you still need anything from this PR, submit it as new PR.

**Pull request closed without merging**
